-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.27 - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2013-03-29 19:31:42
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping database structure for xindi
DROP DATABASE IF EXISTS `xindi`;
CREATE DATABASE IF NOT EXISTS `xindi` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `xindi`;


-- Dumping structure for table xindi.articles
DROP TABLE IF EXISTS `articles`;
CREATE TABLE IF NOT EXISTS `articles` (
  `article_id` int(11) NOT NULL AUTO_INCREMENT,
  `article_slug` varchar(150) DEFAULT NULL,
  `article_title` varchar(150) DEFAULT NULL,
  `article_content` longtext,
  `article_metagenerated` bit(1) DEFAULT NULL,
  `article_metatitle` varchar(200) DEFAULT NULL,
  `article_metadescription` varchar(200) DEFAULT NULL,
  `article_metakeywords` varchar(200) DEFAULT NULL,
  `article_author` varchar(100) DEFAULT NULL,
  `article_published` datetime DEFAULT NULL,
  `article_created` datetime DEFAULT NULL,
  `article_updated` datetime DEFAULT NULL,
  `article_updatedby` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`article_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi.articles: ~3 rows (approximately)
DELETE FROM `articles`;
/*!40000 ALTER TABLE `articles` DISABLE KEYS */;
INSERT INTO `articles` (`article_id`, `article_slug`, `article_title`, `article_content`, `article_metagenerated`, `article_metatitle`, `article_metadescription`, `article_metakeywords`, `article_author`, `article_published`, `article_created`, `article_updated`, `article_updatedby`) VALUES
	(4, 'sample-article-a', 'Sample Article A', '<h1>\r\n	Sample Article A</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Sample Article A', '&nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donu', 'Cookie,dolor,roll,beans,Lemon,muffin,gummi,pudding,Apple,cookie,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,wypas,S', '', '2013-03-01 00:00:00', '2013-03-29 19:21:26', '2013-03-29 19:21:26', 'Default User'),
	(5, 'sample-article-b', 'Sample Article B', '<h1>\r\n	Sample Article B</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Sample Article B', '&nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donu', 'Cookie,dolor,roll,beans,Lemon,muffin,gummi,pudding,Apple,cookie,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,wypas,S', '', '2013-03-01 00:00:00', '2013-03-29 19:21:34', '2013-03-29 19:21:34', 'Default User'),
	(6, 'sample-article-c', 'Sample Article C', '<h1>\r\n	Sample Article C</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Sample Article C', '&nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donu', 'Cookie,dolor,roll,beans,Lemon,muffin,gummi,pudding,Apple,cookie,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,wypas,S', '', '2013-03-01 00:00:00', '2013-03-29 19:21:38', '2013-03-29 19:21:38', 'Default User');
/*!40000 ALTER TABLE `articles` ENABLE KEYS */;


-- Dumping structure for table xindi.enquiries
DROP TABLE IF EXISTS `enquiries`;
CREATE TABLE IF NOT EXISTS `enquiries` (
  `enquiry_id` int(11) NOT NULL AUTO_INCREMENT,
  `enquiry_name` varchar(50) DEFAULT NULL,
  `enquiry_email` varchar(150) DEFAULT NULL,
  `enquiry_message` longtext,
  `enquiry_read` bit(1) DEFAULT NULL,
  `enquiry_created` datetime DEFAULT NULL,
  PRIMARY KEY (`enquiry_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi.enquiries: ~3 rows (approximately)
DELETE FROM `enquiries`;
/*!40000 ALTER TABLE `enquiries` DISABLE KEYS */;
INSERT INTO `enquiries` (`enquiry_id`, `enquiry_name`, `enquiry_email`, `enquiry_message`, `enquiry_read`, `enquiry_created`) VALUES
	(1, 'Simon Bingham', 'example@example.com', 'Phasellus ut tortor in erat dignissim eleifend at nec leo! Praesent vel lectus et elit condimentum hendrerit vel sit amet magna. Nunc luctus bibendum mi sed posuere. Pellentesque facilisis ullamcorper ultrices. Nulla eu dolor ac nunc laoreet tincidunt. Nulla et laoreet eros. Proin id pellentesque justo? Maecenas quis risus augue. Nulla commodo laoreet est nec mattis. Phasellus id dolor quam, id mattis mauris.', b'00000000', '2012-01-01 00:00:00'),
	(2, 'John Whish', 'example@example.com', 'Phasellus ut tortor in erat dignissim eleifend at nec leo! Praesent vel lectus et elit condimentum hendrerit vel sit amet magna. Nunc luctus bibendum mi sed posuere. Pellentesque facilisis ullamcorper ultrices. Nulla eu dolor ac nunc laoreet tincidunt. Nulla et laoreet eros. Proin id pellentesque justo? Maecenas quis risus augue. Nulla commodo laoreet est nec mattis. Phasellus id dolor quam, id mattis mauris.', b'00000000', '2012-01-01 00:00:00'),
	(3, 'Andy Beer', 'example@example.com', 'Phasellus ut tortor in erat dignissim eleifend at nec leo! Praesent vel lectus et elit condimentum hendrerit vel sit amet magna. Nunc luctus bibendum mi sed posuere. Pellentesque facilisis ullamcorper ultrices. Nulla eu dolor ac nunc laoreet tincidunt. Nulla et laoreet eros. Proin id pellentesque justo? Maecenas quis risus augue. Nulla commodo laoreet est nec mattis. Phasellus id dolor quam, id mattis mauris.', b'00000000', '2012-01-01 00:00:00');
/*!40000 ALTER TABLE `enquiries` ENABLE KEYS */;


-- Dumping structure for table xindi.pages
DROP TABLE IF EXISTS `pages`;
CREATE TABLE IF NOT EXISTS `pages` (
  `page_id` int(11) NOT NULL AUTO_INCREMENT,
  `page_slug` varchar(150) DEFAULT NULL,
  `page_left` int(11) DEFAULT NULL,
  `page_right` int(11) DEFAULT NULL,
  `page_ancestorid` int(11) DEFAULT NULL,
  `page_depth` int(11) DEFAULT NULL,
  `page_title` varchar(150) DEFAULT NULL,
  `page_content` longtext,
  `page_metagenerated` bit(1) DEFAULT NULL,
  `page_metatitle` varchar(200) DEFAULT NULL,
  `page_metadescription` varchar(200) DEFAULT NULL,
  `page_metakeywords` varchar(200) DEFAULT NULL,
  `page_created` datetime DEFAULT NULL,
  `page_updated` datetime DEFAULT NULL,
  `page_updatedby` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`page_id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi.pages: ~15 rows (approximately)
DELETE FROM `pages`;
/*!40000 ALTER TABLE `pages` DISABLE KEYS */;
INSERT INTO `pages` (`page_id`, `page_slug`, `page_left`, `page_right`, `page_ancestorid`, `page_depth`, `page_title`, `page_content`, `page_metagenerated`, `page_metatitle`, `page_metadescription`, `page_metakeywords`, `page_created`, `page_updated`, `page_updatedby`) VALUES
	(1, 'home', 1, 18, 0, 1, 'Home', '<h1>\r\n	Welcome to Xindi</h1>\r\n<p>\r\n	<img align="right" alt="" border="2" src="_clientfiles/home/xindi-logo.gif" style="padding:5px; margin:0 0 15px 15px;" /><strong>You have successfully installed Xindi!</strong></p>\r\n<p>\r\n	This is the public facing site which is fully customisable.</p>\r\n<p>\r\n	<a href="./admin" target="_blank">You can access the content management system here</a>. The default email address and password are &#39;admin@getxindi.com&#39; and &#39;password&#39;.</p>\r\n<p>\r\n	If you need support you can:</p>\r\n<ul>\r\n	<li>\r\n		<a href="https://github.com/simonbingham/xindi">View our Wiki and Issue Tracker</a></li>\r\n	<li>\r\n		<a href="https://groups.google.com/forum/?hl=en&amp;fromgroups#!forum/getxindi">Post to our Google Group</a></li>\r\n</ul>\r\n<p>\r\n	To keep up to date with the latest Xindi news:</p>\r\n<ul>\r\n	<li>\r\n		<a href="http://www.getxindi.com/">Visit the Xindi website</a></li>\r\n	<li>\r\n		<a href="https://twitter.com/#!/getxindi">Follow Xindi on Twitter</a></li>\r\n	<li>\r\n		<a href="http://www.facebook.com/getxindi">Find Xindi on Facebook</a></li>\r\n	<li>\r\n		<a href="https://plus.google.com/112798469896267857099/posts">Find Xindi on Google+</a></li>\r\n</ul>\r\n<p>\r\n	I very much welcome contributions to Xindi. If you would like to contribute some code please <a href="http://github.com/simonbingham/xindi">fork the project on GitHub, modify the code and send me a pull request</a>.</p>\r\n<p>\r\n	I hope you enjoy using Xindi.</p>\r\n<p>\r\n	<a href="https://twitter.com/simonbingham">Simon Bingham</a></p>\r\n', b'10000000', 'Home', 'Welcome to Xindi You have successfully installed Xindi! This is the public facing site which is fully customisable. You can access the content management system here . The default email address and pa', 'need,using,send,pull,password,Group,Issue,please,would,Google+,Follow,Wiki,request,GitHub,welcome,fully,contributions,fork,support,Find,here,code,like,Facebook,Visit,much,content,customisable,project,', '2012-01-01 00:00:00', '2013-03-29 19:16:40', 'Default User'),
	(2, 'design', 2, 3, 0, 2, 'Design', '<h1>\r\n	Design</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Design', 'Design &nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly', 'Cookie,dolor,roll,beans,Lemon,muffin,gummi,pudding,Apple,cookie,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,wypas,S', '2012-01-01 00:00:00', '2013-03-29 19:17:48', 'Default User'),
	(3, 'consulting', 4, 11, 0, 2, 'Consulting', '<h1>\r\n	Consulting</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Consulting', 'Consulting &nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. J', 'Cookie,dolor,roll,beans,Lemon,muffin,gummi,pudding,Apple,cookie,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,wypas,S', '2012-01-01 00:00:00', '2013-03-29 19:17:56', 'Default User'),
	(4, 'sample-page-1', 5, 6, 0, 3, 'Sample Page 1', '<h1>\r\n	Sample Page 1</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Sample Page 1', 'Sample Page 1 &nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love', 'Cookie,dolor,roll,beans,Page,Lemon,muffin,gummi,pudding,Apple,cookie,1,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,', '2012-01-01 00:00:00', '2013-03-29 19:18:04', 'Default User'),
	(5, 'sample-page-2', 7, 8, 0, 3, 'Sample Page 2', '<h1>\r\n	Sample Page 2</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Sample Page 2', 'Sample Page 2 &nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love', 'Cookie,dolor,roll,beans,Page,Lemon,muffin,gummi,pudding,Apple,cookie,2,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,', '2012-01-01 00:00:00', '2013-03-29 19:18:11', 'Default User'),
	(6, 'sample-page-3', 9, 10, 0, 3, 'Sample Page 3', '<h1>\r\n	Sample Page 3</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Sample Page 3', 'Sample Page 3 &nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love', 'Cookie,dolor,roll,beans,Page,Lemon,muffin,gummi,pudding,Apple,cookie,3,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,', '2012-01-01 00:00:00', '2013-03-29 19:18:16', 'Default User'),
	(7, 'training', 12, 13, 0, 2, 'Training', '<h1>\r\n	Training</h1>\r\n<p>\r\n	&nbsp;</p>\r\n<div>\r\n	Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jelly-o donut I love chocolate bar faworki liquorice toffee. Oat cake gummi bears chocolate I love biscuit chocolate. Halvah chocolate cake I love gummies jujubes biscuit liquorice powder chocolate cake. Jelly lemon drops jujubes. Pie chocolate bar wypas souffl&eacute; carrot cake jelly-o dessert topping. Macaroon jelly tart gummies. Marshmallow cupcake lollipop topping toffee macaroon sugar plum. Candy canes sweet faworki wafer jelly-o. Chocolate carrot cake icing gingerbread ice cream I love apple pie chocolate bar muffin.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Souffl&eacute; candy canes carrot cake pudding sweet I love. Chocolate cake wafer I love tootsie roll. Donut muffin marshmallow. Caramels tart apple pie I love cookie faworki cotton candy marshmallow wypas. Lollipop ice cream icing dessert wafer donut bear claw. Apple pie drag&eacute;e toffee biscuit sugar plum I love bear claw tootsie roll. Lemon drops powder cotton candy sweet I love jujubes halvah chupa chups toffee. Marshmallow wafer jelly-o gingerbread jelly I love wypas cheesecake lollipop. Carrot cake chocolate cheesecake jelly-o I love liquorice sugar plum. Jelly marshmallow oat cake candy. Bonbon marzipan chupa chups marshmallow applicake carrot cake. Cookie biscuit marshmallow. Biscuit cupcake I love cotton candy.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Jelly-o sugar plum fruitcake apple pie I love lemon drops. Bonbon jelly beans I love marzipan chocolate bar chocolate cake. Applicake wypas souffl&eacute; chocolate cake applicake. Powder croissant dessert brownie carrot cake biscuit carrot cake oat cake. Chocolate cake marzipan pie chupa chups I love. I love pastry halvah jujubes. Chocolate bar candy canes muffin cupcake bear claw. Carrot cake pastry gingerbread gummies. Gummies caramels drag&eacute;e I love jelly-o applicake danish. Carrot cake danish toffee sweet toffee muffin pastry liquorice I love. Applicake lemon drops tiramisu tart candy canes. Chocolate fruitcake gummi bears danish halvah cake.</div>\r\n', b'10000000', 'Training', 'Training &nbsp; Cupcake ipsum dolor sit amet souffl&eacute; marzipan. Danish croissant ice cream drag&eacute;e icing lollipop. I love faworki tootsie roll I love pastry pastry marzipan pie I love. Jel', 'Cookie,dolor,roll,beans,Lemon,muffin,gummi,pudding,Apple,cookie,applicake,Biscuit,jujubes,drag&eacute;e,carrot,faworki,macaroon,bear,Caramels,cheesecake,sit,Lollipop,chocolate,halvah,fruitcake,wypas,S', '2012-01-01 00:00:00', '2013-03-29 19:18:22', 'Default User'),
	(8, 'news', 14, 15, 1, 2, 'News', '<h1>News</h1><p><a href="https://github.com/simonbingham/xindi/wiki/2.-Frequently-Asked-Questions">Follow the instructions on our wiki</a> to make this page redirect to the news feature.</p><p>	Alternatively, you can access the news feature at <a href="index.cfm/news">index.cfm/news</a>.</p>', b'10000000', 'News', 'News You can follow the instructions on our wiki to make this page redirect to the news feature. You can also access the news feature at index.cfm/news .', 'News,You,can,follow,instructions,our,wiki,make,page,redirect,feature,also,access,at,indexcfm/news', '2012-01-01 00:00:00', '2012-01-01 00:00:00', 'Simon Bingham'),
	(9, 'enquiry', 16, 17, 1, 2, 'Contact', '<h1>Contact</h1><p><a href="https://github.com/simonbingham/xindi/wiki/2.-Frequently-Asked-Questions">Follow the instructions on our wiki</a> to make this page redirect to the contact form feature.</p><p>	Alternatively, you can access the contact form feature at <a href="index.cfm/enquiry">index.cfm/enquiry</a>.</p>', b'10000000', 'Contact', 'Contact Follow the instructions on our wiki to make this page redirect to the contact form feature. Alternatively, you can access the contact form feature at index.cfm/e', 'Contact,Follow,instructions,our,wiki,make,page,redirect,form,feature,Alternatively,you,can,access,at,indexcfm/enquiry', '2012-01-01 00:00:00', '2012-01-01 00:00:00', 'Simon Bingham');
/*!40000 ALTER TABLE `pages` ENABLE KEYS */;


-- Dumping structure for table xindi.users
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_name` varchar(50) DEFAULT NULL,
  `user_email` varchar(150) DEFAULT NULL,
  `user_password` varchar(65) DEFAULT NULL,
  `user_created` datetime DEFAULT NULL,
  `user_updated` datetime DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- Dumping data for table xindi.users: ~1 rows (approximately)
DELETE FROM `users`;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`user_id`, `user_name`, `user_email`, `user_password`, `user_created`, `user_updated`) VALUES
	(1, 'Default User', 'admin@getxindi.com', '5119ED792CCFC42DA3F9A5DCF55210E6CD453C7A81FFB52681F62D72022FBE46', '2012-01-01 00:00:00', '2013-03-29 19:11:22');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
